// Generated by CoffeeScript 1.3.3
(function() {
  var actionSelector, addButton, boardNameSelector, cardNameSelector, config, debug, findBoardName, findCardDescription, findIds, findMatch, insertScript, isConfigLoaded, loadConfig, namespacedString, nsClass, nsEvent, nsId, projectNameSelector, sendMessage, setupButton;

  projectNameSelector = 'title:first';

  boardNameSelector = '.js-board-title';

  cardNameSelector = '.window-title-text';

  actionSelector = '.other-actions';

  debug = false;

  isConfigLoaded = false;

  config = "window._harvestPlatformConfig = {    'applicationName': 'Trello',    'permalink': 'https://trello.com/card/%PROJECT_ID%/%ITEM_ID%',    'skipStyling': true,    'debug': " + debug + "  }";

  namespacedString = function(name) {
    return "harvest-" + name;
  };

  nsId = function(name) {
    return "#" + (namespacedString(name));
  };

  nsClass = function(name) {
    return "." + (namespacedString(name));
  };

  nsEvent = function(name) {
    return "" + (namespacedString('event')) + ":" + name;
  };

  sendMessage = function(options) {
    var div, event;
    if (options.element) {
      options.data['element'] = options.element[0];
    }
    event = document.createEvent('CustomEvent');
    event.initCustomEvent(nsEvent(options.type), true, true, options.data);
    div = $("" + (nsId('messaging'))).get(0);
    if (div) {
      return div.dispatchEvent(event);
    }
  };

  insertScript = function(callback) {
    var entry, script;
    script = document.createElement('script');
    script.type = 'text/javascript';
    script.async = true;
    script.innerHTML = config;
    entry = document.getElementsByTagName('script')[0];
    entry.parentNode.insertBefore(script, entry);
    if (script.addEventListener) {
      script.addEventListener('load', callback, false);
    } else {
      script.attachEvent('onreadystatechange', function() {
        if (/complete|loaded/.test(script.readyState)) {
          return callback();
        }
      });
    }
    return isConfigLoaded = true;
  };

  loadConfig = function() {
    var callback, host, url;
    host = debug ? 'harvestapp.dev' : 'platform.harvestapp.com';
    url = "//" + host + "/javascripts/generated/platform.js";
    callback = $.getScript(url);
    return insertScript(callback);
  };





  findMatch = function(pattern) {
    var href, matches;
    href = window.location.href;
    if (href) {
      matches = href.match(pattern);
    }
    if (href) {
      matches = href.match(pattern);
    } else {
      return void 0;
    }
    if (!(matches != null) || matches.length === 0) {
      return void 0;
    } else {
      return matches[1];
    }
  };

  findBoardName = function() {
    return $(boardNameSelector).text();
  };

  findCardDescription = function() {
    return $(cardNameSelector).text();
  };

  findIds = function() {
    var boardIdPattern, cardIdPattern, data;
    boardIdPattern = /^https:\/\/trello.com\/card\/[a-zA-Z0-9-]+\/(\S+)\/\d+$/;
    cardIdPattern = /^https:\/\/trello.com\/card\/[a-zA-Z0-9-]+\/\S+\/(\d+)$/;
    return data = {
      'project': {
        'id': findMatch(boardIdPattern),
        'name': findBoardName()
      },
      'item': {
        'id': findMatch(cardIdPattern),
        'name': findCardDescription()
      }
    };
  };

  addButton = function(element, data) {
    data['element'] = element;
    return sendMessage({
      'type': 'timers:request',
      'data': 'data',
      data: data
    });
  };

  setupButton = function() {
    var data, icon, timer, title;
    data = findIds();
    icon = $('<span></span>').addClass('trello-timer-icon');
    title = " Track time...";
    timer = $("<a></a>").addClass('harvest-timer').addClass('button-link').addClass('js-add-trello-timer').attr('data-project', JSON.stringify(data.project)).attr('data-item', JSON.stringify(data.item)).append(icon).append(title);
    $(actionSelector).children().first().after(timer);
    return addButton(timer, data);
  };

  setupButton();

  loadConfig();

  setInterval(function() {
    var cardPattern, href;
    cardPattern = /^https:\/\/trello.com\/card\/[a-zA-Z0-9-]+\/\S+\/\d+$/;
    href = window.location.href;
    if (href.match(cardPattern) !== null) {
      if ($(".harvest-timer").length === 0) {
        return setupButton();
      }
    }
  }, 250);

}).call(this);
