// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var onRequest;
    onRequest = function(request, sender, callback) {
      var pattern;
      if (request.action === 'showPageAction') {
        pattern = /^http[s]?:\/\/(\S+.)?(basecamp.com|trello.com|jira.com)(\/.*)*/;
        return chrome.tabs.getSelected(null, function(tab) {
          if (tab.url.match(pattern) != null) {
            return chrome.pageAction.show(tab.id);
          }
        });
      }
    };
    return chrome.extension.onRequest.addListener(onRequest);
  });

}).call(this);
